# tag_render.jl
#
# Markdown renderers for the tag index: a per-case table (INDEX.md) and a
# feature-coverage matrix for the Task Force (COVERAGE.md). Included by
# tag_cases.jl after the records are built.

using Dates

_join(v) = isempty(v) ? "—" : join(v, ", ")

# safe read of a solution_profile field (block may be absent/null)
_sp(r, k) = (sp = get(r, "solution_profile", nothing); sp === nothing ? nothing : get(sp, k, nothing))

function write_index_md(records, path)
    open(path, "w") do io
        println(io, "# Benchmark index\n")
        println(io, "_Generated by `scripts/tag_cases.jl` — do not edit by hand._  ")
        println(io, "_Vocabulary and derivation rules: [docs/TAGGING.md](../docs/TAGGING.md). ")
        println(io, "Machine-readable: [tags_index.json](tags_index.json)._\n")
        println(io, "`model_tier` = implementation effort (Table 6). ")
        println(io, "`class` = well-posedness gate (core/watch/pathological). ")
        println(io, "`challenge` = genuine computational load among clean cases (C1–C3, from DOF). ")
        println(io, "These three axes are independent.\n")
        println(io, "| Case | Dataset | Buses | Size | Tier | Class | Challenge | DOF | Active | Strict-comp | Topology | Wires | Neutral | Components | DER | Task | License | Solved |")
        println(io, "|------|---------|------:|:----:|:----:|:-----:|:---------:|----:|-------:|:-----------:|:--------:|:-----:|---------|------------|-----|------|---------|:------:|")
        for r in sort(records; by = x -> (x["dataset"], x["id"]))
            s  = r["structure"]; w = r["wires_grounding"]; l = r["load_der"]
            sv = r["solvability"]; sp = get(r, "solution_profile", nothing)
            solved = (sv === nothing || sv["solved"] === nothing) ? "—" : (sv["solved"] ? "✓" : "✗")
            dof   = sp === nothing ? "—" : something(get(sp, "dof", nothing), "—")
            nact  = sp === nothing ? "—" : something(get(sp, "n_active", nothing), "—")
            sc    = sp === nothing ? "—" : (get(sp, "strict_complementarity", nothing) === nothing ? "—" :
                        (sp["strict_complementarity"] ? "✓" : "✗"))
            println(io, "| `$(r["id"])` | $(r["dataset"]) | $(s["n_buses"]) | $(s["size_class"]) | ",
                "$(r["model_tier"]) | $(r["benchmark_class"]) | $(something(r["challenge"], "—")) | $dof | $nact | $sc | ",
                "$(s["topology"]) | $(_join(w["wires"])) | $(_join(w["neutral_model"])) | $(_join(r["components"])) | ",
                "$(l["der_penetration"]) | $(_join(r["task"])) | $(r["provenance"]["license"]) | $solved |")
        end
        println(io)
    end
end

# Feature-coverage matrix: rows = features/behaviours, columns = dataset families.
# A cell shows how many cases in that family exhibit the feature. Surfaces gaps
# (empty columns) for the Task Force — the "representative networks" motivation.
function write_coverage_md(records, path)
    fam_of(r) = r["dataset"]
    fams = sort(unique(fam_of.(records)))

    # feature predicates (name => (record -> Bool))
    feats = Pair{String,Function}[
        "Tier T1 (baseline)"        => r -> r["model_tier"] == "T1",
        "Tier T2 (delta/xfmr/multi-VL)" => r -> r["model_tier"] == "T2",
        "Tier T3 (voltage-dep loads)"   => r -> r["model_tier"] == "T3",
        "Tier T∞ (ctrl/storage/TS)" => r -> r["model_tier"] == "Tinf",
        "Class: core (recommended)" => r -> r["benchmark_class"] == "core",
        "Class: watch"              => r -> r["benchmark_class"] == "watch",
        "Class: pathological"       => r -> r["benchmark_class"] == "pathological",
        "Genuine OPF (something binds)" => r -> _sp(r, "is_opf") === true,
        "Strictly complementary"    => r -> _sp(r, "strict_complementarity") === true,
        "Degenerate solution"       => r -> _sp(r, "strict_complementarity") === false,
        "Challenge C1 (DOF<200)"    => r -> r["challenge"] == "C1",
        "Challenge C2 (200–2000)"   => r -> r["challenge"] == "C2",
        "Challenge C3 (≥2000)"      => r -> r["challenge"] == "C3",
        "Meshed topology"           => r -> r["structure"]["topology"] == "meshed",
        "Multi voltage level"       => r -> r["structure"]["multi_voltage_level"],
        "4-wire (explicit neutral)" => r -> 4 in r["wires_grounding"]["wires"],
        "3-wire (Kron-reduced)"     => r -> "kron_reduced" in r["wires_grounding"]["neutral_model"],
        "SWER zone"                 => r -> r["wires_grounding"]["swer_zone"],
        "Split-phase zone"          => r -> r["wires_grounding"]["split_phase_zone"],
        "Transformers"              => r -> "transformer" in r["components"],
        "Switches"                  => r -> "switch" in r["components"],
        "Inverters / IBR"           => r -> "inverter" in r["components"],
        "Control profiles (VV/VW)"  => r -> "control_profile" in r["components"],
        "Delta loads"               => r -> "DELTA" in r["load_der"]["load_configs"],
        "Voltage-dependent loads"   => r -> any(m -> m in ("zip","exponential","constant_impedance","constant_current"), r["load_der"]["load_models"]),
        "DER present (>none)"       => r -> r["load_der"]["der_penetration"] != "none",
    ]

    open(path, "w") do io
        println(io, "# Feature-coverage matrix\n")
        println(io, "_Generated by `scripts/tag_cases.jl` — do not edit by hand._  ")
        println(io, "_Each cell = number of cases in that dataset family with the feature. ")
        println(io, "Empty rows/columns are coverage gaps worth filling. See [docs/TAGGING.md](../docs/TAGGING.md)._\n")

        # header
        print(io, "| Feature / behaviour |")
        for f in fams; print(io, " $f |"); end
        println(io, " **Total** |")
        print(io, "|---|")
        for _ in fams; print(io, "--:|"); end
        println(io, "--:|")

        for (name, pred) in feats
            print(io, "| $name |")
            total = 0
            for fam in fams
                n = count(r -> fam_of(r) == fam && pred(r), records)
                total += n
                print(io, " $(n == 0 ? "·" : n) |")
            end
            println(io, " **$total** |")
        end
        println(io)
        println(io, "**Cases per family:** ",
            join(["$fam = $(count(r -> fam_of(r) == fam, records))" for fam in fams], " · "),
            " — total $(length(records)).")
        println(io)
        core = count(r -> r["benchmark_class"] == "core", records)
        println(io, "**Recommended set:** $core / $(length(records)) cases are `core` ",
            "(clean, well-posed, genuinely binding, strictly complementary). ",
            "`watch`/`pathological` cases are kept and labelled for robustness testing — ",
            "see [docs/TAGGING.md](../docs/TAGGING.md).")
        println(io)
        println(io, "> Gaps to note for the Task Force: features with a `·` in every column are ",
            "not yet exercised anywhere in the curated corpus (e.g. delta loads, storage, ",
            "voltage-dependent loads, meshed/multi-VL) — candidate additions when building out ",
            "the benchmark set.")
    end
end
